name: Reusable Deploy
on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download dist dir
              uses: actions/download-artifact@v4
              with:
                name: dist-files
            - name: Output info
              run: echo "Deploying and uploading "